version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 16
    commands:
      - echo Installing dependencies...
      - npm install
  build:
    commands:
      - echo Building application...
      - npm run build
  post_build:
    commands:
      - echo Build successful, preparing deployment...
      - zip -r app.zip dist node_modules package.json
      - aws s3 cp app.zip s3://my-nestjs-app-deployment/
artifacts:
  files:
    - app.zip
