name: Deploy to EC2

on:
  push:
    branches: ['master']

jobs:
  deploy:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'
      - name: Show secrets
        run: |
          echo "Current HOST: ${{ secrets.EC2_HOST  }} "
          echo "Current USER: ${{ secrets.EC2_USER  }} "
          echo "Current PRIVATE_KEY: ${{ secrets.EC2_PRIVATE_KEY  }} "
      - run: npm ci
      - name: Build application
        run: npm run build --if-present
      - name: Deploy to EC2
        env:
          PRIVATE_KEY: ${{ secrets.EC2_PRIVATE_KEY }}
          HOST: ${{ secrets.EC2_HOST }}
          USER: ${{ secrets.EC2_USER }}
        run: |
          echo "$PRIVATE_KEY" > github-ec2.pem && chmod 600 github-ec2.pem
          ssh -o StrictHostKeyChecking=no -i github-ec2.pem ${USER}@${HOST} '
          echo "Current directory: $(pwd)"
          echo "Listing home directory:"
          ls -la ~

          echo "Installing Node.js..."
          if ! command -v nvm &> /dev/null; then
            curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.39.5/install.sh | bash
            export NVM_DIR="$HOME/.nvm"
            [ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"  # This loads nvm
          fi
          nvm install node


          echo "Installing PM2..."
          if ! command -v pm2 &> /dev/null; then
          npm install -g pm2
          fi

          REPO_URL="https://github.com/Rodrigo15975/ec-2"
          BRANCH="master"
          REPO_DIR="$HOME/Rodrigo15975/ec-2"

          if [ -d "$REPO_DIR/.git" ]; then
          cd "$REPO_DIR"
          git pull origin "$BRANCH"
          else
            git clone "$REPO_URL" "$REPO_DIR"
            cd "$REPO_DIR"
          fi

          cd "$REPO_DIR/ec-2"
          npm install

          cd ~/github-aws-ec2/ec-2
          git pull origin master
          npm install

          echo "Starting/restarting application..."
          npm run start:prod
          '
